version: 2.1

name: CircleCI + CodeCov

orbs:
  codecov: codecov/codecov@1

jobs:
  test-java:
    docker:
      - image: maven:3.8.5-openjdk-11
    steps:
      - checkout
      - run:
          name: Calculate cache key
          command: |-
            find . -name 'pom.xml' -o -name 'gradlew*' -o -name '*.gradle*' | \
                    sort | xargs cat > /tmp/CIRCLECI_CACHE_KEY
      - restore_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
      - run:
          command: mvn verify
      - store_test_results:
          path: target/surefire-reports
      - save_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
          paths:
            - ~/.m2/repository
      - codecov/upload




  #deploy:
  #  docker:
  #    - image: cimg/base:stable
  #  steps:
  #    - run:
  #        name: deploy
  #        command: '#e.g. ./deploy.sh'

workflows:
  build-test-and-codecov:
    jobs:
      - test-java
