version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

executors:
  java-executor:
    docker:
      - image: cimg/openjdk:17.0

jobs:
  test-java:
    executor: java-executor
    steps:
      - checkout
      - run:
          name: Calculate cache key
          command: |-
            find . -name 'pom.xml' | sort | xargs cat > /tmp/CIRCLECI_CACHE_KEY
      - restore_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
      - run:
          command: mvn clean install
      - store_test_results:
          path: target/surefire-reports
      - save_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
          paths:
            - ~/.m2/repository

  upload-codecov:
    executor: java-executor
    steps:
      - checkout
      - codecov/upload:
          token: $CODECOV_TOKEN
          file: target/site/jacoco/jacoco.xml

workflows:
  build-and-test:
    jobs:
      - test-java
      - upload-codecov:
          requires:
            - test-java
