version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          mvn clean install
#      - run:
#          name: Calculate cache key
#          command: |-
#            find . -name 'pom.xml' -o -name 'gradlew*' -o -name '*.gradle*' | \
#                    sort | xargs cat > /tmp/CIRCLECI_CACHE_KEY
#      - restore_cache:
#          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
      - run:
          command: mvn verify
#      - store_test_results:
#          path: target/surefire-reports
#      - save_cache:
#          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
#          paths:
#            - ~/.m2/repository
#      - run : mvn jacoco:report
      - run:
          name: Run tests and collect coverage
          command: mvn -B test
      - codecov/upload
#      - run:
#          name: Upload coverage to Codecov
#          command: |-
#            curl -s https://codecov.io/bash | bash -s




  #deploy:
  #  docker:
  #    - image: cimg/base:stable
  #  steps:
  #    - run:
  #        name: deploy
  #        command: '#e.g. ./deploy.sh'

workflow:
  version: 2
  build-test-and-codecov:
    jobs:
      - build
