version: 2.1

name: CircleCI + CodeCov

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  test-java:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Calculate cache key
          command: |-
            find . -name 'pom.xml' -o -name 'gradlew*' -o -name '*.gradle*' | \
                    sort | xargs cat > /tmp/CIRCLECI_CACHE_KEY
      - restore_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
      - run:
          command: mvn verify
      - store_test_results:
          path: target/surefire-reports
      - save_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
          paths:
            - ~/.m2/repository
  codecov:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Upload coverage to Codecov
          command: |-
            curl -s https://codecov.io/bash | bash -s -- -t $CODECOV_TOKEN -f target/site/jacoco/jacoco.xml
          environment:
            CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: deploy
          command: '#e.g. ./deploy.sh'

workflows:
  build-and-test-and-codecov:
    jobs:
      - test-java
      - codecov:
          requires:
            - test-java