version: 2.1

orbs:
  codecov: codecov/codecov@3

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Run Tests
          command: mvn verify
  upload-to-codecov:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Upload coverage to Codecov
          command: |-
            curl -s https://codecov.io/bash | bash -s -f target/site/jacoco/jacoco.xml

workflows:
  version: 2
  build_and_upload:
    jobs:
      - build
      - upload-to-codecov:
          requires:
            - build