version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Build project
          command: mvn clean install
      - run:
          name: Calculate cache key
          command: |-
            find . -name 'pom.xml' -o -name 'gradlew*' -o -name '*.gradle*' | \
              sort | xargs cat > /tmp/CIRCLECI_CACHE_KEY
      - restore_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
      - run:
          command: mvn verify
      - store_test_results:
          path: target/surefire-reports
      - save_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
          paths:
            - ~/.m2/repository
      - run:
          name: Generate Jacoco report
          command: mvn jacoco:report
      - run:
          name: Run tests and collect coverage
          command: mvn -B test
      - run:
          name: Upload coverage to Codecov
          command: |-
            curl -s https://codecov.io/bash | bash -s -- -t $CODECOV_TOKEN -f target/site/jacoco/jacoco.xml -r matheoFauchez/ceri-m1-techniques-de-test

      - run:
          name: Checkstyle
          command: |-
            mvn checkstyle:checkstyle
            violations=$(grep -o "<error" target/checkstyle-result.xml | wc -l)

            if [ "$violations" -eq 0 ]; then
                badge_url="https://img.shields.io/badge/checkstyle-${violations}-green"
            elif [ "$violations" -lt 100 ]; then
                badge_url="https://img.shields.io/badge/checkstyle-${violations}-orange"
            else
                badge_url="https://img.shields.io/badge/checkstyle-${violations}-red"
            fi

            sed -i "s|.*Checkstyle.*|![Checkstyle]($badge_url)|" README.md

            if git diff --cached --quiet; then
              echo "No changes to commit for Checkstyle badge"
            else
              git config --global user.email "matheo.fauchez@alumni.univ-avignon.fr"
              git config --global user.name "matheoFauchez"
              git commit -am "MàJ README.md avec badge checkstyle [skip ci]"
              git push
            fi

      - run:
          name: Generate Javadoc
          command: mvn javadoc:javadoc || true

      - run:
          name: Publish Javadoc to GitHub Pages
          command: |-
            git config --global user.email "matheo.fauchez@alumni.univ-avignon.fr"
            git config --global user.name "matheoFauchez"
            
            mkdir -p target/site/javadoc
            
            cp -r target/reports/apidocs/* target/site/javadoc/
            
            git checkout --orphan gh-pages
            git rm -rf .
            
            cp -r target/site/javadoc/. .
            git add .

            git commit -m "Ajout de la Javadoc [skip ci]"
            git push --force --set-upstream origin gh-pages

workflows:
  build-test-and-codecov:
    jobs:
      - build
