version: 2.1

orbs:
  codecov: codecov/codecov@3

jobs:
  build:
    docker:
      - image: maven:3.8.5-openjdk-11
    steps:
      - checkout
      - run:
          name: Run Tests
          command: mvn verify
  upload-to-codecov:
    docker:
      - image: maven:3.8.5-openjdk-11
    steps:
      - checkout
      - rcodecov/upload

workflows:
  version: 2
  build_and_upload:
    jobs:
      - build
      - upload-to-codecov:
          requires:
            - build