version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Build project
          command: mvn clean install
      - run:
          name: Calculate cache key
          command: |-
            find . -name 'pom.xml' -o -name 'gradlew*' -o -name '*.gradle*' | \
              sort | xargs cat > /tmp/CIRCLECI_CACHE_KEY
      - restore_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
      - run:
          command: mvn verify
      - store_test_results:
          path: target/surefire-reports
      - save_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
          paths:
            - ~/.m2/repository
      - run:
          name: Generate Jacoco report
          command: mvn jacoco:report
      - run:
          name: Run tests and collect coverage
          command: mvn -B test
      - run:
          name: Upload coverage to Codecov
          command: |-
            curl -s https://codecov.io/bash | bash -s -- -t $CODECOV_TOKEN -f target/site/jacoco/jacoco.xml -r matheoFauchez/ceri-m1-techniques-de-test
      - run:
          name: Checkstyle
          command: |-
            mvn checkstyle:checkstyle

      - run:
          name: Count Checkstyle Violations and Create JSON
          command: |-
            violations=$(grep -o '<file.*violations="[0-9]*"' target/checkstyle-result.xml | \
                        sed 's/.*violations="\([0-9]*\)".*/\1/' | \
                        awk '{s+=$1} END {print s}')
            echo "Violations: $violations"

            # Create a JSON file with the violations count
            echo "{\"violations\": $violations}" > checkstyle-violations.json

workflows:
  build-test-and-codecov:
    jobs:
      - build
